import os

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.environ.get("GOOGLE_REDIRECT_URI")

FLASK_SECRET_KEY = os.environ.get("FLASK_SECRET_KEY")
SECRET_KEY = os.environ.get("SECRET_KEY")
